// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TubeMonitor.Api.Data;

#nullable disable

namespace TubeMonitor.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TubeMonitor.Api.Models.Canal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("Inscritos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nicho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.ToTable("Canais", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Handle = "@codigofacil",
                            Inscritos = 185000L,
                            Nicho = "Tecnologia",
                            Nome = "Código Fácil"
                        },
                        new
                        {
                            Id = 2,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Handle = "@cozinha10min",
                            Inscritos = 920000L,
                            Nicho = "Culinária",
                            Nome = "Cozinha em 10 Minutos"
                        },
                        new
                        {
                            Id = 3,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Handle = "@treinoemcasabr",
                            Inscritos = 430000L,
                            Nicho = "Fitness",
                            Nome = "Treino em Casa BR"
                        });
                });

            modelBuilder.Entity("TubeMonitor.Api.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CanalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Comentarios")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Curtidas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublicadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Visualizacoes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanalId");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique();

                    b.ToTable("Videos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CanalId = 1,
                            Comentarios = 412L,
                            Curtidas = 3900L,
                            PublicadoEm = new DateTime(2026, 8, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Titulo = "C# em 15 minutos: do zero à primeira API",
                            Visualizacoes = 48300L,
                            YoutubeVideoId = "cF4sPq9LmZa"
                        },
                        new
                        {
                            Id = 2,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CanalId = 1,
                            Comentarios = 156L,
                            Curtidas = 1820L,
                            PublicadoEm = new DateTime(2026, 8, 28, 18, 0, 0, 0, DateTimeKind.Utc),
                            Titulo = "Entity Framework Core explicado com exemplos",
                            Visualizacoes = 21750L,
                            YoutubeVideoId = "Ht7kWq2NbXe"
                        },
                        new
                        {
                            Id = 3,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CanalId = 2,
                            Comentarios = 1230L,
                            Curtidas = 18400L,
                            PublicadoEm = new DateTime(2026, 8, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Titulo = "Lasanha de frigideira em 10 minutos",
                            Visualizacoes = 312000L,
                            YoutubeVideoId = "Rt9yUi3OpLs"
                        },
                        new
                        {
                            Id = 4,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CanalId = 2,
                            Comentarios = 380L,
                            Curtidas = 6100L,
                            PublicadoEm = new DateTime(2026, 8, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Titulo = "3 cafés da manhã rápidos e baratos",
                            Visualizacoes = 97500L,
                            YoutubeVideoId = "Qw1eRt5YuIo"
                        },
                        new
                        {
                            Id = 5,
                            CadastradoEm = new DateTime(2026, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CanalId = 3,
                            Comentarios = 640L,
                            Curtidas = 9870L,
                            PublicadoEm = new DateTime(2026, 8, 25, 7, 0, 0, 0, DateTimeKind.Utc),
                            Titulo = "Treino de 20 minutos sem equipamento",
                            Visualizacoes = 154200L,
                            YoutubeVideoId = "Zx8cVb4NmAs"
                        });
                });

            modelBuilder.Entity("TubeMonitor.Api.Models.Video", b =>
                {
                    b.HasOne("TubeMonitor.Api.Models.Canal", "Canal")
                        .WithMany("Videos")
                        .HasForeignKey("CanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canal");
                });

            modelBuilder.Entity("TubeMonitor.Api.Models.Canal", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
